list1=[int(input()),input(),int(input())]
list1.append(input())
list2=[int(input()),input(),int(input())]
list2.append(input())
list3=[int(input()),input(),int(input())]
list3.append(input())
list4=[int(input()),input(),int(input())]
list4.append(input())
list5=[int(input()),input(),int(input())]
list5.append(input())
list6=[int(input()),input(),int(input())]
list6.append(input())
list7=[int(input()),input(),int(input())]
list7.append(input())
list8=[int(input()),input(),int(input())]
list8.append(input())
list9=[int(input()),input(),int(input())]
list9.append(input())
list10=[int(input()),input(),int(input())]
list10.append(input())
list11=[list1,list2,list3,list4,list5,list6,list7,list8,list9,list10,]
print(list11)